import Head from "next/head";
import emailjs from "emailjs-com";
import React from 'react';
import ReactDOM from 'react-dom';
import Contact from './contact';


// import { Document, Page } from 'react-pdf';
// import cvPDF from '../public/cv.pdf';



import {
  AiFillFacebook,
  AiFillGithub,
  AiFillLinkedin,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
// import deved from "../public/shanaka.png";

import exp from "../public/exp.svg";
import clients from "../public/clients.svg";
import project from "../public/project.svg";

import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import html from "../public/css.png";
import cSs from "../public/html.png";
import c from "../public/c.png";
import cp from "../public/cp.png";
import py from "../public/python.png";
import reactjs from "../public/react.png";
import r from "../public/r.png";
import shanaka from "../public/shanaka.png";
import github from "../public/github.png";
import git from "../public/git.png";
import kotlin from "../public/kotlin.png";
import android from "../public/Android.png";
import mongo from "../public/mongo.png";
import flutter from "../public/flutter.png";
import figma from "../public/figma.png";
import java from "../public/java.png";
import sql from "../public/sql.png";
import dart from "../public/dart.png";
import scala from "../public/scala.png";
import trello from "../public/trello.png";
import traffic from "../public/traffic.png";
import confolink from "../public/confolink.png";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl  text-gray-800 dark:text-gray-200">Portfolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl  text-gray-800 dark:text-gray-200"
                />
              </li>
              {/* <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li> */}
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="/cv.pdf"
                  download="Shanaka-cv.pdf"
                  >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-1">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Shanaka Fernando
            </h2>
            <h3 className="text-2xl py-2 text-gray-800 dark:text-gray-200 md:text-3xl">
              Computer Science Undergraduate
            </h3>
            

            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-10 md:h-96 md:w-96">
              <Image src={shanaka} layout="fill" objectFit="cover" />
            </div>
            
            <p className="text-md py-10 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Aspiring Software Developer specializing in mobile and web applications. Passionate about creating innovative solutions to real-world challenges. Let's bring your ideas to life!'s get cracking!
            </p>
            
            <div className="text-5xl flex justify-center gap-16 pb- text-gray-600 dark:text-gray-400">
              <a href="https://www.facebook.com/shanakakaushan.fernando" target="_blank">
                <div className="flex justify-center items-center">
                  <AiFillFacebook />
                </div>
              </a>
              <a href="https://github.com/Shanaka1999" target="_blank">
                <div className="flex justify-center items-center">
                  <AiFillGithub />
                </div>
              </a>
              <a href="https://www.linkedin.com/in/shanaka-fernando-249881212/" target="_blank">
                <div className="flex justify-center items-center">
                  <AiFillLinkedin />
                </div>
              </a>
              
            </div>

            

            
            {/* <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-10 md:h-96 md:w-96">
              <Image src={shanaka} layout="fill" objectFit="cover" />
            </div> */}
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl pt-20 pb-5 text-gray-800 dark:text-gray-200 text-center ">More About Me</h3>
            {/* <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              As a beginner mobile and web developer, I am enthusiastic about building 
              functional and user-friendly applications. I'm eager to learn and explore
              new technologies to create captivating digital experiences that make a 
              positive impact. Let's embark on this coding journey together!
            </p> */}
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200 text-center">
               As a beginner-level Software Developer, I am passionate about building web and mobile applications 
               that combine functionality and aesthetics. With a strong foundation in programming and a keen eye
                for detail, I approach each project with enthusiasm and a desire to learn and grow. My determination
                 to solve complex problems, along with effective communication and teamwork skills, drives me to 
                 contribute positively to development projects. Let's collaborate and transform ideas into innovative
                  and user-friendly digital experiences that make a difference
            </p>
          </div>

          
          <div className="lg:flex gap-20">
            <div className="text-center  my-10 flex-1">
              <div className="flex justify-center"> {/* Center the content horizontally */}
                <Image src={exp} width={100} height={100} style={{ fill: 'blue' }} />
              </div>
              <h3 className="text-lg font-medium pt-0  text-teal-500  ">
                Experiences
              </h3>
          
              <h4 className="py-0 text-gray-800 dark:text-gray-300">Beginner</h4>
    
            </div>
            <div className="text-center rounded-xl my-10  flex-1">
              <div className="flex justify-center"> {/* Center the content horizontally */}
                <Image src={clients} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-0  text-teal-500  ">
                Clients
              </h3>
          
              <h4 className="py-0 text-gray-800 dark:text-gray-300">___</h4>
    
            </div>
            
            <div className="text-center   my-10  flex-1">
              <div className="flex justify-center"> {/* Center the content horizontally */}
                <Image src={project} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-0  text-teal-500  ">
                Projects
              </h3>
          
              <h4 className="py-0 text-gray-800 dark:text-gray-300">2 Projects</h4>
    
            </div>
          </div>
        </section>


        <section>
          <div>
            <h3 className="text-3xl pt-10 pb-0 text-gray-800 dark:text-gray-200 text-center ">Skills</h3>
            
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gray-800 flex-1 ">
              
              <h3 className="text-lg font-medium pt-0 pb-2 text-teal-500 ">
                Technical Skills
              </h3>
        
              <div className="text-left pl-20 flex-1 grid grid-cols-2">
              <p className="text-gray-800 dark:text-gray-200 py-1">C/C++</p>
              <p className="text-gray-800 dark:text-gray-200 py-1">Java</p>
              
              <p className="text-gray-800 dark:text-gray-200 py-1">Flutter</p>
              <p className="text-gray-800 dark:text-gray-200 py-1">Figma</p>
              <p className="text-gray-800 dark:text-gray-200 py-1">React JS</p>
              <p className="text-gray-800 dark:text-gray-200 py-1">HTML</p>
              <p className="text-gray-800 dark:text-gray-200 py-1">CSS</p>
              <p className="text-gray-800 dark:text-gray-200 py-1">Git</p>
              <p className="text-gray-800 dark:text-gray-200 py-1">Native Android</p>
              </div>
            </div>

            <div className="text-center shadow-lg p-5 rounded-xl my-10  dark:bg-gray-800 flex-1">
              
              <h3 className="text-lg font-medium pt-0 pb-2 text-teal-500 ">
                Soft Skills
              </h3>
              <p className= "text-gray-800 dark:text-gray-200 py-1">Logical Thinking</p>
              <p className="text-gray-800 dark:text-gray-200 py-1">Creativity</p>
              <p className="text-gray-800 dark:text-gray-200 py-1">Leadership</p>
              <p className="text-gray-800 dark:text-gray-200 py-1">Team Work</p>
              <p className="text-gray-800 dark:text-gray-200 py-1">Quick Learning</p>
              <p className="text-gray-800 dark:text-gray-200 py-1">communication</p>
            </div>



            
          </div>
        </section>


        <section>
          <div>
            <h3 className="text-3xl pt-10 pb-0 text-gray-800 dark:text-gray-200 text-center ">Acedemics & Engagements </h3>
            
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gray-800 flex-1 ">
              
              <h3 className="text-lg font-medium pt-0 pb-2 text-teal-500 ">
                Acedemics
              </h3>
        
              <div className="text-left pl-20 flex-1 ">
              <p className="text-gray-800 dark:text-gray-200 py-0">B.Sc in Computer Science (Ungergraduate)</p>
              <p className="text-gray-800 dark:text-gray-400 pb-5 text-sm"> University of Colombo School of Computing</p>
              <p className="text-gray-800 dark:text-gray-200 py-0">G.C.E. Advanced Level (2019)</p>
              <p className="text-gray-800 dark:text-gray-400 pb-0 text-sm"> Trinity College Kandy (2005-2018)</p>
              <p className="text-gray-800 dark:text-gray-400 pb-5 text-sm"> Physical Science Stream</p>
              </div>
            </div>

            <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gray-800 flex-1 ">
              
              <h3 className="text-lg font-medium pt-0 pb-2 text-teal-500 ">
              Volunteering
              </h3>
        
              <div className="text-left pl-20 flex-1 ">
              <p className="text-gray-800 dark:text-gray-200 pb-2">Rotract</p>
              <p className="text-gray-800 dark:text-gray-400 pb-2 text-sm"> Co-ChairPerson - Turtle's Trail Conservation Project (2023)</p>
              <p className="text-gray-800 dark:text-gray-400 pb-2 text-sm"> Program Team Member - Pahantamba Book Donation Project </p>
              <p className="text-gray-800 dark:text-gray-400 pb-5 text-sm"> Program Team Member - Blood Donation Project</p>
              </div>
            </div>  
          </div>

          <div>
            
            
          </div>

          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gray-800 flex-1 ">
              
              <h3 className="text-lg font-medium pt-0 pb-2 text-teal-500 ">
                Languages
              </h3>
        
              <div className="flex-1 ">
              <p className="text-gray-800 dark:text-gray-200 py-0">Sinhala</p>
              <p className="text-gray-800 dark:text-gray-200 py-0">English</p>
              <p className="text-gray-800 dark:text-gray-200 py-0">Japanese (Basic Knowledge)</p>
              </div>
            </div>

            <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gray-800 flex-1 ">
              
              <h3 className="text-lg font-medium pt-0 pb-2 text-teal-500 ">
              Sports
              </h3>
        
              <div className=" flex-1 ">
              <p className="text-gray-800 dark:text-gray-200 py-0">Athletics</p>
              <p className="text-gray-800 dark:text-gray-200 py-0">Swimming</p>
              </div>
            </div>  
          </div>
        </section>

        {/* <section>
          <div class="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gray-800">
            <h3 class="text-lg font-medium pt-0 pb-2 text-teal-500">Contact Form</h3>
            <form id="contactForm">
            <div>
              <input type="text" name="name" placeholder="Your Name" required class="p-2 rounded-md mb-2 md:w-1/2" />
                <br />
                  <input type="email" name="email" placeholder="Your Email" required class="p-2 rounded-md mb-2 md:w-1/2" />
                <br />
                <textarea name="message" placeholder="Your Message" rows="4" required class="p-2 rounded-md mb-2 md:w-1/2"></textarea>
                <br />
                <button type="submit" class="p-2 rounded-md bg-blue-500 text-white">Submit</button>
            </div>
            </form>
          </div>
      </section> */}


        <section>
          <div>
            <h3 className="text-3xl pt-10 pb-0 text-gray-800 dark:text-gray-200 text-center ">Projects</h3>
            
          </div>

          <div className="lg:flex gap-10">

            <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gray-800 flex-1 ">
              <h3 className="text-lg font-medium pt-0 pb-2 text-teal-500 ">
               NTSF-Mobile
              </h3>
              <div className="flex justify-center"> {/* Center the content horizontally */}
                <Image src={traffic} width={200} height={50} />
              </div>

              <div className="text-left p-2 flex-1 ">
               <p className="text-gray-800 dark:text-gray-200 py-1 text-center">Mobile Application for Adding Spot Fines: Our Java-based native Android app serves as a RESTful platform, enabling law enforcement officers to efficiently issue and manage spot fines, improving accuracy and streamlining the fine payment process.</p>
              </div>

              {/* Buttons Section */}
              <div className="flex justify-center space-x-4 mt-4">
                <a href="https://github.com/Shanaka1999/NTSF-mobile.git" target="_blank" rel="noopener noreferrer" className="bg-gray-600 text-white px-4 py-2 rounded-md">GitHub</a>
                 {/* <a href="https://your_demo_link_here" target="_blank" rel="noopener noreferrer" className="bg-gray-600 text-white px-4 py-2 rounded-md">Demo</a> */}
              </div>
            </div>

            <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gray-800 flex-1 ">
              <h3 className="text-lg font-medium pt-0 pb-2 text-teal-500 ">
               NTSF-Frontend
              </h3>
              <div className="flex justify-center"> {/* Center the content horizontally */}
                <Image src={traffic} width={200} height={50} />
              </div>

              <div className="text-left p-2 flex-1 ">
               <p className="text-gray-800 dark:text-gray-200 py-1 text-center">A web application that efficiently manages offences, spot fines, and allows users to make online payments. The platform streamlines fine processing, ensures accurate record-keeping, and provides a seamless payment experience for users.</p>
              </div>

              {/* Buttons Section */}
              <div className="flex justify-center space-x-4 mt-4">
                <a href="https://github.com/Shanaka1999/NTSF-frontend" target="_blank" rel="noopener noreferrer" className="bg-gray-600 text-white px-4 py-2 rounded-md">GitHub</a>
                 {/* <a href="https://your_demo_link_here" target="_blank" rel="noopener noreferrer" className="bg-gray-600 text-white px-4 py-2 rounded-md">Demo</a> */}
              </div>
            </div>


            <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gray-800 flex-1 ">
              <h3 className="text-lg font-medium pt-0 pb-2 text-teal-500 ">
               NTSF-Backend
              </h3>
              <div className="flex justify-center"> {/* Center the content horizontally */}
                <Image src={traffic} width={200} height={50} />
              </div>

              <div className="text-left p-2 flex-1 ">
               <p className="text-gray-800 dark:text-gray-200 py-1 text-center">The National Traffic Spot Fine System is a Java backend project that manages traffic offences and spot fines with seamless integration for mobile and web applications. It enhances law enforcement operations and ensures efficient fine issuance and secure online payments.</p>
              </div>

              {/* Buttons Section */}
              <div className="flex justify-center space-x-4 mt-4">
                <a href="https://github.com/Shanaka1999/NTSF-backend.git" target="_blank" rel="noopener noreferrer" className="bg-gray-600 text-white px-4 py-2 rounded-md">GitHub</a>
                 {/* <a href="https://your_demo_link_here" target="_blank" rel="noopener noreferrer" className="bg-gray-600 text-white px-4 py-2 rounded-md">Demo</a> */}
              </div>
            </div>  
          </div>


          

          <div className="lg:flex gap-10">

            <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gray-800 flex-1 ">
              <h3 className="text-lg font-medium pt-0 pb-2 text-teal-500 ">
               Confolink-Mobile
              </h3>
              <div className="flex justify-center"> {/* Center the content horizontally */}
                <Image src={confolink} width={200} height={50} />
              </div>

              <div className="text-left p-2 flex-1 ">
               <p className="text-gray-800 dark:text-gray-200 py-1 text-center">Confolink is a Flutter-based mobile app designed for efficient conference management, seamless communication, streamlined event coordination, and networking opportunities, all in the palm of your hand.</p>
              </div>

              {/* Buttons Section */}
              <div className="flex justify-center space-x-4 mt-4">
                {/* <a href="https://github.com/Shanaka1999/NTSF-mobile.git" target="_blank" rel="noopener noreferrer" className="bg-gray-600 text-white px-4 py-2 rounded-md">GitHub</a> */}
                 <a href="https://youtu.be/LOJ_7FQBnrg" target="_blank" rel="noopener noreferrer" className="bg-gray-600 text-white px-4 py-2 rounded-md">Demo</a>
              </div>
            </div>

            <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gray-800 flex-1 ">
              <h3 className="text-lg font-medium pt-0 pb-2 text-teal-500 ">
               Confolink-Web
              </h3>
              <div className="flex justify-center"> {/* Center the content horizontally */}
                <Image src={confolink} width={200} height={50} />
              </div>

              <div className="text-left p-2 flex-1 ">
               <p className="text-gray-800 dark:text-gray-200 py-1 text-center">The web application is a React-based platform for efficient conference management. With dynamic user interfaces and streamlined coordination, it simplifies conference organization and enhances user experience.</p>
              </div>

              {/* Buttons Section */}
              <div className="flex justify-center space-x-4 mt-4">
                {/* <a href="https://github.com/Shanaka1999/NTSF-frontend" target="_blank" rel="noopener noreferrer" className="bg-gray-600 text-white px-4 py-2 rounded-md">GitHub</a> */}
                 <a href="https://youtu.be/LOJ_7FQBnrg" target="_blank" rel="noopener noreferrer" className="bg-gray-600 text-white px-4 py-2 rounded-md">Demo</a>
              </div>
            </div>


            <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gray-800 flex-1 ">
              <h3 className="text-lg font-medium pt-0 pb-2 text-teal-500 ">
               Confolink-Backend
              </h3>
              <div className="flex justify-center"> {/* Center the content horizontally */}
                <Image src={confolink} width={200} height={50} />
              </div>

              <div className="text-left p-2 flex-1 ">
               <p className="text-gray-800 dark:text-gray-200 py-1 text-center">Confolink's backend, implemented using Java Spring Boot and connected to a MongoDB database, ensures seamless data handling and robust backend functionalities for the application.</p>
              </div>

              {/* Buttons Section */}
              <div className="flex justify-center space-x-4 mt-4">
                {/* <a href="https://github.com/Shanaka1999/NTSF-backend.git" target="_blank" rel="noopener noreferrer" className="bg-gray-600 text-white px-4 py-2 rounded-md">GitHub</a> */}
                 <a href="https://youtu.be/LOJ_7FQBnrg" target="_blank" rel="noopener noreferrer" className="bg-gray-600 text-white px-4 py-2 rounded-md">Demo</a>
              </div>
            </div>  
          </div>





        </section>



        <section>
          <div>
            <h3 className="text-3xl pt-10 pb-5 text-gray-800 dark:text-gray-300 text-center">Technologies Used</h3>
            
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-5 rounded-xl my-10  dark:bg-gray-800 flex-1">
              
              <div className="flex justify-center"> {/* Center the content horizontally */}
                <Image src={html} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-5 pb-1  text-gray-800 dark:text-gray-300 ">
                HTML
              </h3>
              
            </div>
            <div className="text-center shadow-lg p-5 rounded-xl my-10  dark:bg-gray-800 flex-1">
              <div className="flex justify-center"> {/* Center the content horizontally */}
                <Image src={cSs} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-5 pb-1  text-gray-800 dark:text-gray-300 ">
                CSS
              </h3>
            </div>
            <div className="text-center shadow-lg p-5 rounded-xl my-10  dark:bg-gray-800 flex-1">
              <div className="flex justify-center"> {/* Center the content horizontally */}
                <Image src={cp} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-5 pb-1  text-gray-800 dark:text-gray-300 ">
                C++
              </h3>
            </div>
            <div className="text-center shadow-lg p-5 rounded-xl my-10  dark:bg-gray-800 flex-1">
              <div className="flex justify-center"> {/* Center the content horizontally */}
                <Image src={c} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-5 pb-1  text-gray-800 dark:text-gray-300 ">
                C
              </h3>
            </div>
            <div className="text-center shadow-lg p-5 rounded-xl my-10  dark:bg-gray-800 flex-1">
              <div className="flex justify-center"> {/* Center the content horizontally */}
                <Image src={reactjs} width={75} height={75} />
              </div>
              <h3 className="text-lg font-medium pt-5 pb-1  text-gray-800 dark:text-gray-300 ">
                React 
              </h3>
            </div>
            <div className="text-center shadow-lg p-5 rounded-xl my-10  dark:bg-gray-800 flex-1">
              <div className="flex justify-center"> {/* Center the content horizontally */}
                <Image src={py} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-5 pb-1  text-gray-800 dark:text-gray-300 ">
                Python
              </h3>
            </div>

            

            


    
          </div>


          

          
          <div className="lg:flex gap-10">
          <div className="text-center shadow-lg p-5 rounded-xl my-10  dark:bg-gray-800 flex-1">
              <div className="flex justify-center"> {/* Center the content horizontally */}
                <Image src={figma} width={35} height={50} />
              </div>
              <h3 className="text-lg font-medium pt-5 pb-1  text-gray-800 dark:text-gray-300 ">
                Figma
              </h3>
              </div>
            <div className="text-center shadow-lg p-5 rounded-xl my-10  dark:bg-gray-800 flex-1">
              <div className="flex justify-center"> {/* Center the content horizontally */}
                <Image src={android} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-5 pb-1  text-gray-800 dark:text-gray-300 ">
                Native Android
              </h3>
            </div>
            <div className="text-center shadow-lg p-5 rounded-xl my-10  dark:bg-gray-800 flex-1">
              <div className="flex justify-center"> {/* Center the content horizontally */}
                <Image src={flutter} width={40} height={50} />
              </div>
              <h3 className="text-lg font-medium pt-5 pb-1  text-gray-800 dark:text-gray-300 ">
                Flutter
              </h3>
            </div>
            <div className="text-center shadow-lg p-5 rounded-xl my-10  dark:bg-gray-800 flex-1">
              <div className="flex justify-center"> {/* Center the content horizontally */}
                <Image src={mongo} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-5 pb-1  text-gray-800 dark:text-gray-300 ">
                MongoDB
              </h3>
            </div>

            

            
            <div className="text-center shadow-lg p-5 rounded-xl my-10  dark:bg-gray-800 flex-1">
              <div className="flex justify-center"> {/* Center the content horizontally */}
                <Image src={github} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-5 pb-1  text-gray-800 dark:text-gray-300 ">
                Git & GitHub
              </h3>
            </div>

            <div className="text-center shadow-lg p-5 rounded-xl my-10  dark:bg-gray-800 flex-1">
              <div className="flex justify-center"> {/* Center the content horizontally */}
                <Image src={trello} width={80} height={80} />
              </div>
              <h3 className="text-lg font-medium pt-5 pb-1  text-gray-800 dark:text-gray-300 ">
                Trello & Jira
              </h3>
            </div>

          </div>

          {/* //////////////////////////// */}

          
          <div className="lg:flex gap-10">
          <div className="text-center shadow-lg p-5 rounded-xl my-10  dark:bg-gray-800 flex-1">
              <div className="flex justify-center"> {/* Center the content horizontally */}
                <Image src={kotlin} width={60} height={60} />
              </div>
              <h3 className="text-lg font-medium pt-5 pb-1  text-gray-800 dark:text-gray-300 ">
                Kotlin
              </h3>
              </div>
            <div className="text-center shadow-lg p-5 rounded-xl my-10  dark:bg-gray-800 flex-1">
              <div className="flex justify-center"> {/* Center the content horizontally */}
                <Image src={java} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-5 pb-1  text-gray-800 dark:text-gray-300 ">
                Java
              </h3>
            </div>
            {/* <div className="text-center shadow-lg p-5 rounded-xl my-10  dark:bg-gray-800 flex-1">
              <div className="flex justify-center"> 
                <Image src={r} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-5 pb-1  text-gray-800 dark:text-gray-300 ">
                R
              </h3>
            </div> */}
            <div className="text-center shadow-lg p-5 rounded-xl my-10  dark:bg-gray-800 flex-1">
              <div className="flex justify-center"> {/* Center the content horizontally */}
                <Image src={dart} width={40} height={40} />
              </div>
              <h3 className="text-lg font-medium pt-5 pb-1  text-gray-800 dark:text-gray-300 ">
                Dart
              </h3>
            </div>

            {/* <div className="text-center shadow-lg p-5 rounded-xl my-10  dark:bg-gray-800 flex-1">
              <div className="flex justify-center">
                <Image src={scala} width={35} height={35} />
              </div>
              <h3 className="text-lg font-medium pt-5 pb-1  text-gray-800 dark:text-gray-300 ">
                Scala
              </h3>
            </div> */}

            
            <div className="text-center shadow-lg p-5 rounded-xl my-10  dark:bg-gray-800 flex-1">
              <div className="flex justify-center"> {/* Center the content horizontally */}
                <Image src={sql} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-5 pb-1  text-gray-800 dark:text-gray-300 ">
                MySQL
              </h3>
            </div>
          </div>

          {/* ////////////////////////////////////////////////////////// */}





        </section>


        <section>

        <div className="lg:flex gap-10">
        
            <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gray-800 flex-1 ">
              
              <h3 className="text-left text-lg font-medium pt-0 pb-5 text-teal-500  ">
                Contact Details
              </h3>
        
              
              
              <div>
              <p className="text-gray-500 dark:text-gray-400 py-0 pt-5 text-left">Name</p>
              <p className="text-gray-800 dark:text-gray-200 pb-5 text-left">Shanaka Fernando</p>
              <p className="text-gray-500 dark:text-gray-400 py-0 text-left">Mobile</p>
              <p className="text-gray-800 dark:text-gray-200 pb-5 text-left">(+94) 718853934</p>
              <p className="text-gray-500 dark:text-gray-400 py-0 text-left">E-mail</p>
              <p className="text-gray-800 dark:text-gray-200 pb-5 text-left">shanaka2686@gmail.com</p>
              <p className="text-gray-500 dark:text-gray-400 py-0 text-left">Linkedin</p>
              <p className="text-gray-800 dark:text-gray-200 pb-0 text-left">
              <a href="https://www.linkedin.com/in/shanaka-k-fernando" target="_blank" rel="noopener noreferrer">
                  Click to view my Linkedin
              </a>
              </p>
              </div>

              </div>
              

              
              
              
            

            <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-gray-800 flex-1 ">
              
              <h3 className="text-lg font-medium pt-0 pb-2 text-teal-500 ">
              Send me a message
              </h3>

      <section>

  {/* ReactDOM.render( */}
  <React.StrictMode>
    <div id="root ">
    
      
      <Contact />
    </div>
  </React.StrictMode>
  {/* ,
  document.getElementById('root') */}
{/* ); */}


              </section>
        
  


            </div>

          </div>
          
        </section>

        



<section className="py-10">

</section>


      </main>
    </div>
  );


  
}
